---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uykhexishl/public_html/digitalpampas.com/
    - /bin/cp -R . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
